language: python
sudo: false
addons:
  apt:
    packages:
      # Only used by the DISTRIB="ubuntu" setting
      - libatlas3gf-base
      - libatlas-dev
      - python-scipy
env:
  matrix:
    # This environment tests the newest supported anaconda env
    - DISTRIB="conda" PYTHON_VERSION="2.7" INSTALL_MKL="true"
      NUMPY_VERSION="1.9.2" SCIPY_VERSION="0.15.1"
install:
  - source continuous_integration/install.sh
script: nosetests
after_success:
    # Ignore coveralls failures as the coveralls server is not very reliable
    # but we don't want travis to report a failure in the github UI just
    # because the coverage report failed to be published.
    - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi